# Generated by Django 4.1.5 on 2024-07-21 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tablelist', '__first__'),
        ('customers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('booktable_id', models.AutoField(primary_key=True, serialize=False)),
                ('booktable_date', models.DateField()),
                ('booktable_time', models.TimeField()),
                ('booktable_guests', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablelist.tablelist')),
            ],
        ),
    ]
