# Generated by Django 4.1.5 on 2024-07-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_username', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(default='default@example.com', max_length=255, unique=True)),
                ('customer_password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
