# Generated by Django 4.1.5 on 2024-07-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablelist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablelist',
            name='admin_id',
        ),
    ]
